### ISSUE TITLE
우리는 어떻게 애플리케이션 레벨의 로그를 정제하고 사용했을까?

### ISSUE THREAD

**Issue by yeomyaloo** [I-m-YeomSu/imyeomsu-lck#86]
# ELK란?
- `Elasticsearch`, `Logstash`, `Kibana`는 모두 Elastic Stack (ELK 스택)의 구성 요소로, 데이터를 수집, 분석 및 시각화하기 위한 오픈 소스 플랫폼입니다. 
- 해당 3가지를 함께 앞 글자의 첫 문장을 합쳐서 ELK 라고합니다.
### 1. k8s에서의 EFK
- EFK라고 하는 Elasticsearch, fluentbit(fluentd), Kibana가 있습니다. 
  - 해당 기능은 쿠버네티스 환경에서 로그스태시 대신 플루언트 빗을 사용해서 진행한다고 합니다.
  - 또한 쿠버네티스 환경에서는 더 적합한 것이 플루언트 빗이지만 로그 스태시 역시 사용 가능하기 때문에 우선은 로그 스태시를 이용해서 진행했습니다.

### 2. 프로메테우스와 그라파나
- 프로메테우스(Prometheus)와 그라파나(Grafana)는 모니터링을 위한 도구입니다. 
- 프로메테우스는 상태 데이터를 수집하고, 그라파나는 프로메테우스로 수집한 데이터를 관리자가 보기 좋게 시각화합니다.

# Spring이 제공하는 막강한 AOP 기능
### 1. AOP 코드
```java
@Aspect
@Component
@Slf4j
public class RequestAdvisor {

	@Around("execution(* imyeom_lck..*Controller.*(..))")
	public Object requestLogging(ProceedingJoinPoint pjp) throws Throwable {

		HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.currentRequestAttributes()).getRequest();
		// 요청 시간
		long requestTime = System.currentTimeMillis();
		// 요청 URL
		String requestUrl = request.getRequestURL().toString();
		// 요청 메소드
		String requestMethod = request.getMethod();
		// 사용자 IP 주소
		String clientIp = request.getRemoteAddr();
		// 사용자 세션 ID
		HttpSession session = request.getSession();
		String sessionId = session.getId();

		Object result = pjp.proceed();

		log.info("Request Time: " + requestTime);
		log.info("Request URL: " + requestUrl);
		log.info("Request Method: " + requestMethod);
		log.info("Client IP: " + clientIp);
		log.info("Session ID: " + sessionId);

		return result;
	}
}
```
![image](https://github.com/I-m-YeomSu/imyeomsu-lck/assets/81970382/45e9f26c-b6c8-48f8-8fcf-ff0e502ba700)
- 1차적으로 AOP를 이용해서 로그 정제 작업을 했습니다.

# EKS 환경에서의 Filebeat, ELK
![image](https://github.com/I-m-YeomSu/imyeomsu-lck/assets/81970382/6c0dd1f3-8fc3-48f4-b488-09130a1e0ec5)
### 2 . yml 파일
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: lck
data:
  filebeat.yml: |
    setup.template.name: "my_custom_template"
    setup.template.pattern: "my_custom_pattern-*"

    filebeat.inputs:
    - type: filestream
      id: logback
      enabled: true
      paths:
       /usr/share/filebeat/logall/logback/*

      fields:
        index: "logback_index"
      fields_under_root: true

    - type: filestream
      id: access
      enabled: true
      paths:
        /usr/share/filebeat/logall/access/*
      fields:
        index: "access_index"
      fields_under_root: true

    - type: filestream
      id: request
      enabled: true
      paths:
        /usr/share/filebeat/logall/request/*
      fields:
        index: "request_index"
      fields_under_root: true

    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false

    processors:
      - add_cloud_metadata: ~
      - add_docker_metadata: ~

    output.elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]
      username: "elastic"
      password: "elasticstack"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lck-spring
  namespace: lck
spec:
  selector:
    matchLabels:
      app: lck-spring
  template:
    metadata:
      labels:
        app: lck-spring
    spec:
      containers:
        - name: lck-spring
          image: 도커허브아이디/이미지명:태그
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logall
              mountPath: /logall
        - name: filebeat
          image: elastic/filebeat:7.17.20
          volumeMounts:
            - name: logall
              mountPath: /usr/share/filebeat/logall
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml  # ConfigMap의 특정 파일을 사용
      volumes:
        - name: logall
          hostPath:
            path: /var/logall  # 공유할 호스트 경로
        - name: filebeat-config
          configMap:
            name: filebeat-config  # 위에서 정의한 ConfigMap의 이름
---
apiVersion: v1
kind: Service
metadata:
  name: lck-spring
  namespace: lck
spec:
  selector:
    app: lck-spring
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: filebeat-service
  namespace: lck
spec:
  ports:
    - name: filebeat-http
      port: 9200
      targetPort: 9200
    - name: filebeat-tcp
      port: 9300
      targetPort: 9300
    - name: filebeat-logstash
      port: 5044
      targetPort: 5044
  selector:
    app: filebeat

```
- 젠킨스를 통해 CD(배포) 작업을 진행할 때 스프링부트 프로젝트와 함께 파일비트가 붙어서 배포될 수 있게 한다.

### 1. ConfigMap
```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  labels:
    task: logging
    k8s-app: logstash
data:
  logstash.yml: |
    http.host: "127.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
   
   output {
	    if [index] == "catalina_index" {
	        elasticsearch {
	            hosts => ["http://elasticsearch-master:9200"]
	            index => "catalina_index-%{+yyyy.MM.dd}"
	            ssl => true
							ssl_certificate_verification => true
							
							user => "elastic"
							password => "elasticstack"
	        }
	    } else if [index] == "access_index" {
	        elasticsearch {
	            hosts => ["http://elasticsearch-master:9200"]
	            index => :"access_index-%{+yyyy.MM.dd}"
	            ssl => true
							ssl_certificate_verification => true
							
							user => "elastic"
							password => "elasticstack"
	        }
	    } else if [index] == "request_index" {
	        elasticsearch {
	            hosts => ["http://elasticsearch-master:9200"]
	            index => "request_index-%{+yyyy.MM.dd}"
	            ssl => true
							ssl_certificate_verification => true
							
							user => "elastic"
							password => "elasticstack"
	        }
	    }
	}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: elastic/logstash:7.17.20
        ports:
        - name: logstash-tcp
          containerPort: 5044
        imagePullPolicy: IfNotPresent # Always, Never
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/logstash/config
        - name: logstash-pipeline-volume
          mountPath: /usr/share/logstash/pipeline
        - name: tz-seoul
          mountPath: /etc/localtime
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      - name: config-volume
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.conf
            path: logstash.conf
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  clusterIP: None
  ports:
  - name: logstash-tcp
    port: 5044
  - name: logstash-estcp
    port: 9300
  - name: logstash-eshttp
    port: 9200
  selector:
    app: logstash

```
## Elasticsearch
```yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elastic/elasticsearch:7.17.20
        env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: "elasticstack"
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.transport.ssl.enabled
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms500m -Xmx1000m"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: elastic-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elastic-data
        emptyDir:
          sizeLimit: 5Gi
---
# Kibana 또는 타 플랫폼에서 사용할 서비스

apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-master
spec:
  ports:
  - name: elasticsearch
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: elisticsearch-ssl
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
  type: ClusterIP
```
![image](https://github.com/I-m-YeomSu/imyeomsu-lck/assets/81970382/88e5275a-d914-470e-bdb7-0f660046323a)

## Kibana
- 해당 작업을 통해서 가시화하는 것을 진행하였다.
- 여러 정제되어 들어온 데이터를 예쁘게 대시보드를 이용해서 만들어주면 된다.

# 최종 어드민 페이지 
https://github.com/I-m-YeomSu/imyeomsu-lck/assets/81970382/a685422b-c141-4594-bcc2-3eacf113d74a
