### ISSUE TITLE
jacoco와 coveralls를 이용한 테스트 커버리지 확인 작업

### ISSUE THREAD

**Issue by yeomyaloo** [I-m-YeomSu/imyeomsu-lck#95]
# 테스트 커버리지
## 왜 테스트 커버리지를 측정하였을까?
- 우리팀은 테스트 커버리지 80프로 달성이라는 목표로 기능 구현 후에 구현한 기능에 대한 단위 테스트를 진행하였습니다.
- 또한 후에 종합 테스트를 진행함에 따라서 단위 테스트 -> 종합 테스트를 통한 기능의 안정성을 확보했습니다.
 
### JaCoCo
-자바 코드 커버리지를 체크하는 라이브러리입니다.
- 테스트 실행 후 커버리지 결과를 여러 형태(ex. HTML)의 파일로 생성해줍니다.

### Coveralls
- 웹 기반의 코드 커버리지 관리 사이트입니다.
- jacoco가 테스트 커버리지에 대한 결과물을 여러 형태의 파일로 제공한다면 이 제공된 파일을 coveralls로 올려주면 해당 커버리지에 대한 정보를 가시화하여 확인할 수 있게 해줍니다.
- 이때 해당 웹 사이트를 이용해서 프로젝트의 커버리지를 확인하기 위해서는 CI 툴과의 연동이 필수 입니다.

### Git Actions를 이용한 테스트 커버리지 파일 CI 작업
- 생성된 커버리지 관련 파일을 프로젝트가 가지고 있다고 끝나는 것이 아닌 추가적으로 coveralls를 이용해서 이를 확인하고자 한다면 CI 툴을 사용해서 CI 작업을 진행해야 합니다.)
- 우리 팀은 가장 간편하게 사용 가능하고 추가적으로 인프라 구성이 필요 없는 Git Actions를 이용한 test coverage CI 작업을 진행하고자 했습니다.

### 1. build.gradle
```
plugins {
	id 'org.asciidoctor.jvm.convert' version '3.3.2'
	id 'jacoco'
	id 'com.github.kt3k.coveralls' version '2.12.2'
	id 'maven-publish'
}

java {
	sourceCompatibility = '17'
}
bootJar{
	archivesBaseName = 'imyeomsu-lck'
	archiveFileName = 'imyeomsu-lck.jar'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

ext {
	set('snippetsDir', file("build/generated-snippets"))
}

jacoco {
	toolVersion = "0.8.12"
	reportsDirectory = layout.buildDirectory.dir('customJacocoReportDir')
}

test {
	finalizedBy jacocoTestReport 
	ignoreFailures = true
}

jacocoTestReport {
	reports {
		dependsOn test
		reports {
			html.required = true
			xml.required = true
		}

		// QueryDSL QDomain 제외시키기
		def QDomains = []

		for (qPattern in '**/QA'..'**/QZ') {
			QDomains.add(qPattern + '*')
		}
		afterEvaluate {
			classDirectories.setFrom(
					// 그 외의 매칭되는 클래스도 제외 대상
					files(classDirectories.files.collect {
						fileTree(dir: it, excludes: [
								"co.kirikiri.domain.**.**",
								"**/*Application*",
								"**/*Config*",
								"**/*Dto*",
								"**/*Request*",
								"**/*Response*",
								"**/*Interceptor*",
								"**/*Exception*"
						] + QDomains)
					})
			)
		}
	}
}

coveralls {
	jacocoReportPath 'build/customJacocoReportDir/test/jacocoTestReport.xml'
}

tasks.named('test') {
	outputs.dir snippetsDir
	useJUnitPlatform()

	finalizedBy jacocoTestReport

}

tasks.named('asciidoctor') {
	inputs.dir snippetsDir
	dependsOn test
}
```
- build 시 jacoco가 내놓을 xml 형식의 테스트 커버리지 파일의 경로를 잡아줍니다.
![image](https://github.com/I-m-YeomSu/imyeomsu-lck/assets/81970382/a6cfe269-b7a3-421e-acf2-42dad893e702)
- jacoco가 만들어준 xml 파일

### 2. git actions 설정
```
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5

  coveralls:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set execute permission for Gradle Wrapper
        run: chmod +x ./gradlew
      - name: Coveralls GitHub Action
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run:
          # 혹시 빌드하는 repo가 root가 아니면 cd 명령어를 통해 이동해주자.
          # cd (빌드하는 repo의 경로)
          ./gradlew clean test jacocoTestReport coveralls

```

## 최종 이미지
![image](https://github.com/I-m-YeomSu/imyeomsu-lck/assets/81970382/b3bda126-a0bd-4322-990d-f98c9c3ac339)
